spring:
  application:
    name: boot_insitude
  # mongo dataSource config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog

  jackson:
    default-property-inclusion: non_empty

  # multiDataSource config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      primary:
        url: jdbc:mysql://localhost:3306/primary
        username: root
        password: 1234
        driverClass: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

      slave:
        url: jdbc:mysql://localhost:3306/slave
        username: root
        password: 1234
        driverClass: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

      job-log:
        url: jdbc:mysql://localhost:3306/job_log
        username: root
        password: 1234
        driverClass: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
      filter:
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
          wall:
              config:
                  multi-statement-allow: true
                  none-base-statement-allow: true
  #rabbitmq config
  rabbitmq:
    host: 211.159.161.12
    port: 5672
    username: hsh
    password: 123456
    virtual-host: /

  redis:
    host: 192.168.61.2
    port: 6379
    database: 6
    jedis:
      pool:
        max-active: 10
        max-idle: 500
        max-wait: 1
        min-idle: 0
    timeout: 5000
    cluster:
      max-redirects: 3
      nodes: 192.168.61.2:6379,192.168.61.61:6379,103.10.87.235:6379

  #elasticsearch config
  elasticsearch:
    jest:
      uris: http://47.104.158.165:9200
      connection-timeout: 10000
      multi-threaded: true

# server port
server:
  port: 9099

# logging xml config location
logging:
  config: classpath:logback.xml

# dubbo config
dubbo:
  application:
    name: boot_provider
  scan:
    package: com.hsh.dubbo
  registry:
    address: zookeeper://211.159.161.12:2181
  protocol:
    name: dubbo
    port: 20880



mybatis:
  mapper-locations: com/hsh/mapping/*.xml
